version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-master
    ports:
      - 3307:3306
    volumes:
      - ./conf/master/:/etc/mysql/:ro
      - ./data/master/:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root

  slave:
    image: mysql:latest
    container_name: mysql-slave
    ports:
      - 3308:3306
    volumes:
      - ./conf/slave/:/etc/mysql/:ro
      - ./data/slave/:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root
